### ISSUE TITLE
Watchtower date api

### ISSUE THREAD

**Issue by SulpherStaer** [eosfrontier/eos-beacon#4]
Beacon still requires manual adjustment with date and time, watchtower also does, but if beacon had watchtower integration, it is more inline with the intended flow of the IT systems.

**Comment by SulpherStaer** [comment]
Beacon should use the Watchtower date API to set it's date.

Currently it sets it manually.

**Comment by WafflesMcDuff** [comment]
I can probably do this. The code is on https://github.com/eosfrontier/eos-beacon/blob/master/public/mainScreen.html#L89 and will just require hitting  https://api.eosfrontier.space/watchtower/time/ and parsing the data

**Comment by SulpherStaer** [comment]
I could do it too, quite easily, as it is lifting code from the dashboard. But since this is Thijs' app, I didn't want to just do it.
Though I now realise I could just make a branch and do a merge request.

(Accidently clicked close issue and comment, rather than comment. Github is weird making the close issue the green button)

**Comment by SulpherStaer** [comment]
https://github.com/eosfrontier/eos-beacon/pull/11
